name: CI/CD - Epibuilder Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
      core: ${{ steps.changes.outputs.core }}
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        run: |
          git fetch origin main
          CHANGED=$(git diff --name-only origin/main ${{ github.sha }})

          echo "frontend=$(echo \"$CHANGED\" | grep '^frontend/' || echo '')" >> $GITHUB_OUTPUT
          echo "backend=$(echo \"$CHANGED\" | grep '^backend/' || echo '')" >> $GITHUB_OUTPUT
          echo "core=$(echo \"$CHANGED\" | grep '^core/' || echo '')" >> $GITHUB_OUTPUT

      - name: Show changed modules
        run: |
          echo "Core changed:     [${{ steps.changes.outputs.core != '' }}]"
          echo "Backend changed:  [${{ steps.changes.outputs.backend != '' }}]"
          echo "Frontend changed: [${{ steps.changes.outputs.frontend != '' }}]"
          
  build-core:
    needs: detect-changes
    if: needs.detect-changes.outputs.core != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
          cache: 'maven'
      - name: Build core
        run: |
          cd core
          mvn clean package
          mkdir -p ../core-build
          cp target/epibuilder-core-jar-with-dependencies.jar ../core-build/epibuilder-core.jar

  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
          cache: 'maven'
      - name: Build backend
        run: |
          cd backend
          mvn package -DskipTests
          mkdir -p ../backend-build
          cp target/*.jar ../backend-build/epibuilder-backend.jar

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          mkdir -p ../frontend-build/dist/frontend
          cp -r dist/frontend/* ../frontend-build/dist/frontend/

  docker-build:
    needs: [detect-changes, build-core, build-backend, build-frontend]
    if: needs.detect-changes.outputs.core != '' || needs.detect-changes.outputs.backend != '' || needs.detect-changes.outputs.frontend != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare build context
        run: |
          mkdir build
          [ -d backend-build ] && cp -r backend-build build/backend
          [ -d core-build ] && cp -r core-build build/core
          [ -d frontend-build ] && cp -r frontend-build build/frontend
          cp -r pipeline build/pipeline
          cp bepipred3.zip build/
          cp requirements.txt build/
          cp nginx.conf build/
          cp entrypoint.sh build/
          cp epibuilder.sh build/

      - name: Build & push Docker images (debian-cpu)
        run: |
          cd build
          docker buildx build --push \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            -f ../Dockerfile.debian \
            -t ${{ secrets.DOCKER_USERNAME }}/epibuilder:debian-cpu-${{ github.sha }} \
            -t ${{ secrets.DOCKER_USERNAME }}/epibuilder:debian-cpu .

      - name: Build & push Docker images (ubuntu-gpu)
        run: |
          cd build
          docker buildx build --push \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            -f ../Dockerfile.ubuntu \
            -t ${{ secrets.DOCKER_USERNAME }}/epibuilder:ubuntu-gpu-${{ github.sha }} \
            -t ${{ secrets.DOCKER_USERNAME }}/epibuilder:ubuntu-gpu .
